//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.ArticleTag = new HashSet<ArticleTag>();
            this.Comment = new HashSet<Comment>();
        }
    
        public long id { get; set; }
        public long blogId { get; set; }
        public string MediaUrl { get; set; }
        public Nullable<long> MediaTypeId { get; set; }
        public string Text { get; set; }
    
        public virtual Blog Blog { get; set; }
        public virtual MediaType MediaType { get; set; }
        public virtual ICollection<ArticleTag> ArticleTag { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
    }
}
