//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public Blog()
        {
            this.Article = new HashSet<Article>();
            this.Follow = new HashSet<Follow>();
        }
    
        public long id { get; set; }
        public long UserId { get; set; }
        public long StyleId { get; set; }
        public long ThemeId { get; set; }
        public string Nom { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Article> Article { get; set; }
        public virtual Style Style { get; set; }
        public virtual Theme Theme { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Follow> Follow { get; set; }
    }
}
