//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public long id { get; set; }
        public long UserId { get; set; }
        public long ArticleId { get; set; }
        public string Comment1 { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual User User { get; set; }
    }
}
