//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_Article> T_Article { get; set; }
        public DbSet<T_ArticleTag> T_ArticleTag { get; set; }
        public DbSet<T_Blog> T_Blog { get; set; }
        public DbSet<T_Comment> T_Comment { get; set; }
        public DbSet<T_Follow> T_Follow { get; set; }
        public DbSet<T_MediaType> T_MediaType { get; set; }
        public DbSet<T_Style> T_Style { get; set; }
        public DbSet<T_Tag> T_Tag { get; set; }
        public DbSet<T_Theme> T_Theme { get; set; }
        public DbSet<T_User> T_User { get; set; }
    }
}
