//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Article
    {
        public T_Article()
        {
            this.T_ArticleTag = new HashSet<T_ArticleTag>();
            this.T_Comment = new HashSet<T_Comment>();
        }
    
        public long Id { get; set; }
        public long BlogId { get; set; }
        public string MediaUrl { get; set; }
        public Nullable<long> MediaTypeId { get; set; }
        public string Text { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual T_Blog T_Blog { get; set; }
        public virtual T_MediaType T_MediaType { get; set; }
        public virtual ICollection<T_ArticleTag> T_ArticleTag { get; set; }
        public virtual ICollection<T_Comment> T_Comment { get; set; }
    }
}
