//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ArticleTag
    {
        public long Id { get; set; }
        public long TagId { get; set; }
        public long ArticleId { get; set; }
    
        public virtual T_Article T_Article { get; set; }
        public virtual T_Tag T_Tag { get; set; }
    }
}
