//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Blog
    {
        public T_Blog()
        {
            this.T_Article = new HashSet<T_Article>();
            this.T_Follow = new HashSet<T_Follow>();
        }
    
        public long Id { get; set; }
        public long UserId { get; set; }
        public long StyleId { get; set; }
        public long ThemeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual ICollection<T_Article> T_Article { get; set; }
        public virtual T_Style T_Style { get; set; }
        public virtual T_Theme T_Theme { get; set; }
        public virtual T_User T_User { get; set; }
        public virtual ICollection<T_Follow> T_Follow { get; set; }
    }
}
