//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MediaType
    {
        public T_MediaType()
        {
            this.T_Article = new HashSet<T_Article>();
        }
    
        public long Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<T_Article> T_Article { get; set; }
    }
}
