//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Style
    {
        public T_Style()
        {
            this.T_Blog = new HashSet<T_Blog>();
            this.T_User = new HashSet<T_User>();
        }
    
        public long Id { get; set; }
        public string CSSPath { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<T_Blog> T_Blog { get; set; }
        public virtual ICollection<T_User> T_User { get; set; }
    }
}
