//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Tag
    {
        public T_Tag()
        {
            this.T_ArticleTag = new HashSet<T_ArticleTag>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<T_ArticleTag> T_ArticleTag { get; set; }
    }
}
