//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_User
    {
        public T_User()
        {
            this.T_Blog = new HashSet<T_Blog>();
            this.T_Comment = new HashSet<T_Comment>();
            this.T_Follow = new HashSet<T_Follow>();
        }
    
        public long Id { get; set; }
        public long StyleId { get; set; }
        public string Login { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Email { get; set; }
        public string HashPassword { get; set; }
    
        public virtual ICollection<T_Blog> T_Blog { get; set; }
        public virtual ICollection<T_Comment> T_Comment { get; set; }
        public virtual ICollection<T_Follow> T_Follow { get; set; }
        public virtual T_Style T_Style { get; set; }
    }
}
